# Generated by Django 2.1.7 on 2019-03-21 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeeprofile_id'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='empl_pr',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='employee.EmployeeProfile'),
            preserve_default=False,
        ),
    ]
