# Generated by Django 2.1.7 on 2019-03-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeeprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='Record_Status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Record Status'),
        ),
    ]
