# Generated by Django 2.1.7 on 2019-03-21 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0003_auto_20190321_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GoalsName', models.CharField(default='-', max_length=200, verbose_name='GoalsName')),
                ('Metrics', models.CharField(default='-', max_length=100, verbose_name='GoalsName')),
                ('Percent', models.FloatField(default=0.0, max_length=100, verbose_name='Percent')),
                ('Weight', models.FloatField(default=0.0, max_length=100, verbose_name='Weight')),
                ('StartDate', models.DateField(default=django.utils.timezone.now)),
                ('Status', models.IntegerField(default=0, verbose_name='Status')),
                ('Actual', models.CharField(default='-', max_length=100, verbose_name='Actual')),
                ('Target', models.TextField(default='-')),
                ('worker', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
